version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./etc/php/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8001:8000"
  app_supervisor:
    build:
      context: .
      dockerfile: ./etc/supervisor/Dockerfile
    volumes:
      - ./:/var/www

  # mail trap app
  mailhog:
    image: mailhog/mailhog:latest
    volumes:
      - mailhog:/maildir
    ports:
      - "1025:1025" #smtp server
      - "8025:8025" #web ui

volumes:
  mailhog: